# Generated by Django 4.0 on 2022-01-06 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0004_todomodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todomodel',
            name='snsimage',
        ),
    ]
